name: build and release

on:
  push:
    tags:
      # - v[0-9]+.[0-9]+.[0-9]+
      - test

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x

      - name: Build
        run: |
          go build -o gpio-shutdown
          mv scripts/gpio-shutdown.service ./
          zip -r gpio-shutdown.zip gpio-shutdown gpio-shutdown.service

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./gpio-shutdown.zip
          asset_name: gpio-shutdown.zip
          asset_content_type: application/zip
